server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: message-service

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:message-group}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

  data:
    cassandra:
      contact-points: ${SPRING_DATA_CASSANDRA_CONTACT_POINTS}
      port: ${SPRING_DATA_CASSANDRA_PORT}
      keyspace-name: ${SPRING_DATA_CASSANDRA_KEYSPACE_NAME}
      local-datacenter: ${SPRING_DATA_CASSANDRA_LOCAL_DATACENTER}
      schema-action: ${SPRING_DATA_CASSANDRA_SCHEMA_ACTION:CREATE_IF_NOT_EXISTS}

management:
  endpoints:
    web:
      exposure:
        include: "*"